import type { NoteTelemetry, TelemetrySnapshot } from "./types";

const stages = [
  { index: 0, ksp: 0, dvAtmo: 500, dvVac: 650, twr: 0.8, twrAtmo: 0.8, twrVac: 1.0, burn: 42 },
  { index: 1, ksp: 1, dvAtmo: 0, dvVac: 0, twr: 0, twrAtmo: 0, twrVac: 0, burn: 0 },
  { index: 2, ksp: 2, dvAtmo: 1000, dvVac: 1200, twr: 1.25, twrAtmo: 1.25, twrVac: 1.55, burn: 75 },
];

const activeNote: NoteTelemetry = {
  name: "log_Odyssey",
  relativePath: "log_Odyssey.txt",
  modified: 1784311200,
  size: 2048,
  text: "MET 00:02:14\nOrbit insertion complete.\nCrew reports nominal systems.",
  truncated: false,
};

const notesFixture = {
  "notes.available": true,
  "notes.activeFound": true,
  "notes.message": "",
  "notes.active": activeNote,
  "notes.selected": activeNote,
  "notes.selectedPath": activeNote.relativePath,
  "notes.selectionMode": "active" as const,
  "notes.pinned": null,
  "notes.pinnedPath": "",
  "notes.catalog": [
    {
      name: "Crew Checklist",
      relativePath: "Crew Checklist.txt",
      isActiveLog: false,
      isFavorite: true,
    },
    {
      name: activeNote.name,
      relativePath: activeNote.relativePath,
      isActiveLog: true,
      isFavorite: false,
    },
  ],
  "notes.catalogTruncated": false,
};

export const flightTelemetryFixture: TelemetrySnapshot = {
  "context.mode": "flight",
  "flight.active": true,
  "krpc.throttle": 0.68,
  "krpc.currentStage": 2,
  "v.name": "Odyssey",
  "v.body": "Kerbin",
  "v.missionTime": 134.2,
  "v.altitude": 82_415.6,
  "v.verticalSpeed": 128.4,
  "v.surfaceSpeed": 2_215.3,
  "v.orbitalVelocity": 2_287.1,
  "v.geeForce": 1.08,
  "v.situationString": "Orbiting",
  "v.biome": "Midlands",
  "t.universalTime": 9_493_824,
  "n.heading": 91.8,
  "n.pitch": 4.2,
  "n.roll": -1.4,
  "o.ApA": 104_238.4,
  "o.PeA": 78_614.7,
  "o.timeToAp": 312.8,
  "o.timeToPe": 1_084.5,
  "o.inclination": 0.43,
  "o.eccentricity": 0.0187,
  "o.period": 1_397.6,
  "krpc.sas": false,
  "krpc.sasMode": "SASMode.stability_assist",
  "mj.sasActive": true,
  "mj.sasMode": "SmartASSAutopilotMode.orbit_prograde",
  "rt.available": true,
  "rt.hasConnection": true,
  "rt.signalDelay": 0.083,
  "comm.krpc.canCommunicate": true,
  "comm.krpc.signalStrength": 0.94,
  "res.names": ["LiquidFuel", "Oxidizer", "ElectricCharge", "ZeroCapacityModResource"],
  "r.resource[LiquidFuel]": 90,
  "r.resourceMax[LiquidFuel]": 100,
  "r.resourceCurrent[LiquidFuel]": 45,
  "r.resourceCurrentMax[LiquidFuel]": 50,
  "r.resource[Oxidizer]": 110,
  "r.resourceMax[Oxidizer]": 120,
  "r.resourceCurrent[Oxidizer]": 55,
  "r.resourceCurrentMax[Oxidizer]": 60,
  "r.resource[ElectricCharge]": 825,
  "r.resourceMax[ElectricCharge]": 1000,
  "r.resourceCurrent[ElectricCharge]": 225,
  "r.resourceCurrentMax[ElectricCharge]": 300,
  "r.resource[ZeroCapacityModResource]": 0,
  "r.resourceMax[ZeroCapacityModResource]": 0,
  "res.stageKnown": true,
  "stage.available": true,
  "stage.complete": true,
  "stage.pending": false,
  "stage.currentKsp": 2,
  "stage.stages": stages,
  "stage.totalDvAtmo": 1500,
  "stage.totalDvVac": 1850,
  "heat.backend": "system_heat",
  "heat.generatedKw": 284.2,
  "heat.removedKw": 301.6,
  "heat.netKw": -17.4,
  "heat.loops": [
    { id: "1", tempK: 612.4, genKw: 184.2, remKw: 201.6 },
    { id: "2", tempK: 428.1, genKw: 100, remKw: 100 },
  ],
  "elec.reactors": [
    { name: "MX-2C Hyperion Fission Reactor", on: true, status: "Online", ecPerSec: 36.4, ecMax: 40, coreTemp: 905, nominalTemp: 900, integrity: 98.7, fuel: "12y 184d", throttle: 91 },
    { name: "MX-1B Hermes Fission Reactor", on: false, status: "Offline", ecPerSec: 0, ecMax: 18, coreTemp: 411, nominalTemp: 850, integrity: 100, fuel: "24y 12d", throttle: 0 },
  ],
  "elec.totalGenEcPerSec": 48.6,
  "elec.otherEcPerSec": 1.2,
  "solar.count": 4,
  "solar.outputEcPerSec": 9.8,
  "solar.efficiency": 0.87,
  "rtg.count": 1,
  "rtg.outputEcPerSec": 1.2,
  "sci.krpc.total": 42.7,
  "sci.krpc.transmitTotal": 19.4,
  "sci.krpc.count": 3,
  "sci.krpc.experiments": [
    { title: "Mystery Goo observation from space near Kerbin", value: 18.2, transmit: 5.5, data: 10 },
    { title: "Temperature scan from high space over Kerbin", value: 14.5, transmit: 11.6, data: 8 },
    { title: "Crew report from space near Kerbin", value: 10, transmit: 2.3, data: 5 },
  ],
  "sci.krpc.backend": "VesselScience",
  "career.science": 384.7,
  "tar.name": "Odyssey Station",
  "tar.type": "dockingport",
  "tar.distance": 184.6,
  "tar.o.relativeVelocity": 2.3,
  "tar.o.velocity": 2_291.4,
  "tar.o.ApA": 105_812,
  "tar.o.PeA": 79_212,
  "tar.o.inclination": 0.51,
  "dock.x": 0.8,
  "dock.y": -0.4,
  "dock.axial": 184.5,
  "dock.ax": 2.1,
  "dock.ay": -1.3,
  ...notesFixture,
  "notes.pinned": activeNote,
  "notes.pinnedPath": activeNote.relativePath,
};

export const editorTelemetryFixture: TelemetrySnapshot = {
  "context.mode": "editor",
  "flight.active": false,
  "editor.craftName": "Dual-condition regression craft",
  "editor.facility": "VAB",
  "editor.body": "Kerbin",
  "editor.bodies": ["Kerbin", "Mun", "Minmus", "Duna"],
  "editor.altitude": 0,
  "editor.mach": 0,
  "editor.revision": 7,
  "editor.stable": true,
  "editor.summaryAvailable": true,
  "editor.partCount": 31,
  "editor.crewCapacity": 3,
  "editor.stageCount": 3,
  "editor.wetMass": 18.742,
  "editor.dryMass": 7.416,
  "editor.resourceMass": 11.326,
  "editor.totalCost": 42580,
  "editor.dryCost": 39740,
  "editor.resourceCost": 2840,
  "editor.res.names": ["ElectricCharge", "LiquidFuel", "Oxidizer", "MonoPropellant"],
  "editor.res[ElectricCharge]": 1200,
  "editor.resMax[ElectricCharge]": 1200,
  "editor.res[LiquidFuel]": 810,
  "editor.resMax[LiquidFuel]": 810,
  "editor.res[Oxidizer]": 990,
  "editor.resMax[Oxidizer]": 990,
  "editor.res[MonoPropellant]": 30,
  "editor.resMax[MonoPropellant]": 30,
  "stage.available": true,
  "stage.complete": true,
  "stage.pending": false,
  "stage.currentKsp": 2,
  "stage.stages": stages,
  "stage.totalDvAtmo": 1500,
  "stage.totalDvVac": 1850,
  ...notesFixture,
};

export const fractionalStageElectricChargeFixture: TelemetrySnapshot = {
  ...flightTelemetryFixture,
  "v.name": "Untitled Space Craft",
  "res.names": ["ElectricCharge", "LiquidFuel", "Oxidizer"],
  "r.resource[ElectricCharge]": 6421.2319,
  "r.resourceMax[ElectricCharge]": 6430.6001,
  "r.resourceCurrent[ElectricCharge]": 0,
  "r.resourceCurrentMax[ElectricCharge]": 0.4,
  "r.resource[LiquidFuel]": 2160,
  "r.resourceMax[LiquidFuel]": 2160,
  "r.resourceCurrent[LiquidFuel]": 1440,
  "r.resourceCurrentMax[LiquidFuel]": 1440,
  "r.resource[Oxidizer]": 2640,
  "r.resourceMax[Oxidizer]": 2640,
  "r.resourceCurrent[Oxidizer]": 1760,
  "r.resourceCurrentMax[Oxidizer]": 1760,
  "res.stageResourceStage": 1,
  "stage.currentKsp": 3,
};

export const inactiveTelemetryFixture: TelemetrySnapshot = {
  "context.mode": "inactive",
  "flight.active": false,
  "v.name": "",
  "t.universalTime": 9_493_824,
  "overview.scene": "Tracking Station",
  "overview.gameMode": "Career",
  "overview.readOnly": true,
  "overview.capabilities": { funds: true, science: true, reputation: true, contracts: true },
  "overview.funds": 1_284_650,
  "overview.science": 384.7,
  "overview.reputation": 72.4,
  "overview.contractCounts": { active: 3, offered: 5, completed: 28, failed: 1 },
  "overview.contracts": [
    { title: "Explore Duna", type: "Exploration", deadline: 13_200_000 },
    { title: "Position a satellite in polar orbit", type: "Satellite", deadline: 10_800_000 },
    { title: "Gather temperature data from Minmus", type: "Science", deadline: 11_400_000 },
  ],
  "overview.vessels": [
    { name: "Odyssey", type: "Ship", situation: "Orbiting", body: "Kerbin", met: 134.2, crewCount: 3, mission: true },
    { name: "Mun Surveyor", type: "Probe", situation: "Orbiting", body: "Mun", met: 282_844, crewCount: 0, mission: true },
    { name: "Duna Relay 1", type: "Relay", situation: "Orbiting", body: "Duna", met: 2_488_000, crewCount: 0, mission: true },
    { name: "Kerbin Gateway", type: "Station", situation: "Orbiting", body: "Kerbin", met: 1_282_000, crewCount: 6, mission: true },
    { name: "Minmus Hopper", type: "Lander", situation: "Landed", body: "Minmus", met: 92_300, crewCount: 2, mission: true },
    { name: "Duna Pathfinder", type: "Rover", situation: "Landed", body: "Duna", met: 3_104_000, crewCount: 0, mission: true },
    { name: "KSC Survey Plane", type: "Plane", situation: "Flying", body: "Kerbin", met: 8_420, crewCount: 1, mission: true },
    { name: "Minmus Research Base", type: "Base", situation: "Landed", body: "Minmus", met: 846_000, crewCount: 4, mission: true },
    { name: "Jebediah Kerman", type: "EVA", situation: "Orbiting", body: "Kerbin", met: 780, crewCount: 1, mission: true },
    { name: "Kerbin Orbital Tug", type: "Ship", situation: "Orbiting", body: "Kerbin", met: 184_200, crewCount: 2, mission: true },
    { name: "Moho Scanner", type: "Probe", situation: "Orbiting", body: "Moho", met: 4_824_000, crewCount: 0, mission: true },
    { name: "Ike Relay 2", type: "Relay", situation: "Orbiting", body: "Ike", met: 2_812_000, crewCount: 0, mission: true },
    { name: "Mun Polar Rover", type: "Rover", situation: "Landed", body: "Mun", met: 382_000, crewCount: 0, mission: true },
    { name: "KSC Flag", type: "Flag", situation: "Landed", body: "Kerbin", met: 5_122_000, crewCount: 0, mission: false },
    { name: "Spent Kerbodyne Stage", type: "Debris", situation: "Sub Orbital", body: "Kerbin", met: 1_240, crewCount: 0, mission: false },
    { name: "Comet SWM-204", type: "Space Object", situation: "Orbiting", body: "Sun", met: 8_422_000, crewCount: 0, mission: false },
  ],
  "overview.vesselsTruncated": false,
  "overview.rosterAvailable": true,
  "overview.roster": [
    { name: "Jebediah Kerman", status: "Assigned", type: "Crew", trait: "Pilot", experience: 18.2, level: 3, veteran: true, flightCount: 8 },
    { name: "Bill Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 9.5, level: 2, veteran: true, flightCount: 5 },
    { name: "Bob Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 12.1, level: 2, veteran: true, flightCount: 6 },
    { name: "Valentina Kerman", status: "Dead", type: "Crew", trait: "Pilot", experience: 22, level: 4, veteran: true, flightCount: 11 },
    { name: "Linus Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 4.2, level: 1, veteran: false, flightCount: 2 },
    { name: "Wernher Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 7.1, level: 2, veteran: false, flightCount: 4 },
    { name: "Gene Kerman", status: "Assigned", type: "Crew", trait: "Pilot", experience: 15.8, level: 3, veteran: false, flightCount: 7 },
    { name: "Mortimer Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 2.5, level: 1, veteran: false, flightCount: 1 },
    { name: "Walt Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 6.4, level: 2, veteran: false, flightCount: 3 },
    { name: "Gus Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 11.2, level: 2, veteran: false, flightCount: 5 },
    { name: "Ed Kerman", status: "Assigned", type: "Crew", trait: "Pilot", experience: 8.7, level: 2, veteran: false, flightCount: 4 },
    { name: "Al Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 3.8, level: 1, veteran: false, flightCount: 2 },
    { name: "Werner Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 5.6, level: 1, veteran: false, flightCount: 3 },
  ],
  "overview.alarms": [
    { title: "Odyssey maneuver", type: "Maneuver", time: 9_496_400, source: "Stock", vessel: "Odyssey" },
    { title: "Mun Surveyor SOI change", type: "SOI Change", time: 9_520_000, source: "KAC", vessel: "Mun Surveyor" },
  ],
  "overview.alarmProviders": { stock: "available", kac: "available" },
  "overview.refreshSeconds": { economy: 2, alarms: 2, fleet: 5, contracts: 10, roster: 15 },
  ...notesFixture,
};
