import type { NoteTelemetry, TelemetrySnapshot } from "./types";
import { representativeElectricityFixture } from "../electricityPlanner/fixtures";

const editorStages = [
  { index: 0, ksp: 0, dvAtmo: 500, dvVac: 650, twr: 0.8, twrAtmo: 0.8, twrVac: 1.0, burn: 42 },
  { index: 1, ksp: 1, dvAtmo: 0, dvVac: 0, twr: 0, twrAtmo: 0, twrVac: 0, burn: 0 },
  { index: 2, ksp: 2, dvAtmo: 1000, dvVac: 1200, twr: 1.25, twrAtmo: 1.25, twrVac: 1.55, burn: 75 },
];

const flightStages = editorStages.map((stage) => ({
  ...stage,
  dvAtmo: stage.dvVac,
  twr: stage.twrVac,
  twrAtmo: stage.twrVac,
  twrStart: stage.twrVac,
  twrEnd: stage.twrVac > 0 ? stage.twrVac * 1.45 : 0,
}));

const denseEditorStages = [
  { index: 0, ksp: 0, dvAtmo: 500, dvVac: 650, twr: 0.8, twrAtmo: 0.8, twrVac: 1.0, burn: 42 },
  { index: 1, ksp: 1, dvAtmo: 0, dvVac: 0, twr: 0, twrAtmo: 0, twrVac: 0, burn: 0 },
  { index: 2, ksp: 2, dvAtmo: 640, dvVac: 780, twr: 0.95, twrAtmo: 0.95, twrVac: 1.15, burn: 51 },
  { index: 3, ksp: 3, dvAtmo: 820, dvVac: 980, twr: 1.08, twrAtmo: 1.08, twrVac: 1.32, burn: 58 },
  { index: 4, ksp: 4, dvAtmo: 0, dvVac: 0, twr: 0, twrAtmo: 0, twrVac: 0, burn: 0 },
  { index: 5, ksp: 5, dvAtmo: 1000, dvVac: 1200, twr: 1.25, twrAtmo: 1.25, twrVac: 1.55, burn: 75 },
  { index: 6, ksp: 6, dvAtmo: 720, dvVac: 890, twr: 1.42, twrAtmo: 1.42, twrVac: 1.68, burn: 48 },
  { index: 7, ksp: 7, dvAtmo: 240, dvVac: 300, twr: 1.58, twrAtmo: 1.58, twrVac: 1.88, burn: 20 },
  { index: 8, ksp: 8, dvAtmo: 360, dvVac: 440, twr: 1.76, twrAtmo: 1.76, twrVac: 2.08, burn: 29 },
  { index: 9, ksp: 9, dvAtmo: 180, dvVac: 230, twr: 2.1, twrAtmo: 2.1, twrVac: 2.45, burn: 12 },
];

const activeNote: NoteTelemetry = {
  name: "log_Odyssey",
  relativePath: "log_Odyssey.txt",
  modified: 1784311200,
  size: 2048,
  text: "MET 00:02:14\nOrbit insertion complete.\nCrew reports nominal systems.",
  truncated: false,
};

const notesFixture = {
  "notes.available": true,
  "notes.activeFound": true,
  "notes.message": "",
  "notes.active": activeNote,
  "notes.selected": activeNote,
  "notes.selectedPath": activeNote.relativePath,
  "notes.selectionMode": "active" as const,
  "notes.pinned": null,
  "notes.pinnedPath": "",
  "notes.catalog": [
    {
      name: "Crew Checklist",
      relativePath: "Crew Checklist.txt",
      isActiveLog: false,
      isFavorite: true,
    },
    {
      name: activeNote.name,
      relativePath: activeNote.relativePath,
      isActiveLog: true,
      isFavorite: false,
    },
  ],
  "notes.catalogTruncated": false,
};

export const flightTelemetryFixture: TelemetrySnapshot = {
  "context.mode": "flight",
  "flight.active": true,
  "identity.available": true,
  "game.saveFolder": "WMC Fixture Save",
  "v.guid": "11111111-2222-3333-4444-555555555555",
  "v.persistentId": "9001",
  "v.rootPartPersistentId": "1001",
  "v.partPersistentIds": ["1001", "1002", "1003"],
  "krpc.throttle": 0.68,
  "krpc.currentStage": 2,
  "v.name": "Odyssey",
  "v.body": "Kerbin",
  "v.missionTime": 134.2,
  "v.altitude": 82_415.6,
  "v.verticalSpeed": 128.4,
  "v.surfaceSpeed": 2_215.3,
  "v.thrust": 680_000,
  "v.availableThrust": 1_000_000,
  "v.orbitalVelocity": 2_287.1,
  "v.geeForce": 1.08,
  "v.situationString": "Orbiting",
  "v.biome": "Midlands",
  "t.universalTime": 9_493_824,
  "n.heading": 91.8,
  "n.pitch": 4.2,
  "n.roll": -1.4,
  "o.ApA": 104_238.4,
  "o.PeA": 78_614.7,
  "o.timeToAp": 312.8,
  "o.timeToPe": 1_084.5,
  "o.inclination": 0.43,
  "o.eccentricity": 0.0187,
  "o.period": 1_397.6,
  "krpc.sas": false,
  "krpc.sasMode": "SASMode.stability_assist",
  "mj.sasActive": true,
  "mj.sasMode": "SmartASSAutopilotMode.orbit_prograde",
  "rt.available": true,
  "rt.hasConnection": true,
  "rt.signalDelay": 0.083,
  "comm.krpc.canCommunicate": true,
  "comm.krpc.signalStrength": 0.94,
  "damage.status": "known",
  "damage.source": "vessel_damage",
  "damage.parts": [
    { kind: "antenna", name: "RFL-100 Giant Dish Reflector", module: "ModuleDeployableReflector", condition: "damaged", count: 24 },
    { kind: "radiator", name: "XR-175 High Temperature Heat Radiator", module: "ModuleDeployableRadiator", condition: "damaged", count: 12 },
  ],
  "damage.checkedKinds": [],
  "damage.incompleteKinds": [],
  "damage.unsupportedKinds": [],
  "damage.checkedCount": 36,
  "damage.checkedModuleCount": 36,
  "damage.readErrorCount": 0,
  "damage.detectors": ["ModuleDeployablePart.deployState"],
  "damage.damagedCount": 36,
  "damage.lossStatus": "known",
  "damage.lossEvents": [{
    eventId: "fixture-cleared-fin",
    partId: 42020,
    name: "AV-R8 Winglet",
    partName: "winglet3",
    kind: "wing",
    state: "cleared",
    occurrenceUt: 12335,
    occurrenceMet: 112,
    clearedUt: 12358,
    clearReason: "intentional_separation",
    cause: "joint_break",
  }],
  "res.names": ["LiquidFuel", "Oxidizer", "ElectricCharge", "ZeroCapacityModResource"],
  "res.status": "known",
  "r.resource[LiquidFuel]": 90,
  "r.resourceMax[LiquidFuel]": 100,
  "r.resourceCurrent[LiquidFuel]": 45,
  "r.resourceCurrentMax[LiquidFuel]": 50,
  "r.resource[Oxidizer]": 110,
  "r.resourceMax[Oxidizer]": 120,
  "r.resourceCurrent[Oxidizer]": 55,
  "r.resourceCurrentMax[Oxidizer]": 60,
  "r.resource[ElectricCharge]": 825,
  "r.resourceMax[ElectricCharge]": 1000,
  "r.resourceCurrent[ElectricCharge]": 225,
  "r.resourceCurrentMax[ElectricCharge]": 300,
  "r.resource[ZeroCapacityModResource]": 0,
  "r.resourceMax[ZeroCapacityModResource]": 0,
  "res.stageKnown": true,
  "stage.available": true,
  "stage.complete": true,
  "stage.pending": false,
  "stage.count": 3,
  "stage.currentKsp": 2,
  "stage.activeKsp": 2,
  "stage.unpoweredCount": 1,
  "stage.totalBurnSeconds": 117,
  "stage.staticPressureAtm": 0,
  "stage.altitude": 82_415.6,
  "stage.body": "Kerbin",
  "stage.situation": "Orbiting",
  "stage.throttle": 0.68,
  "stage.stages": flightStages,
  "stage.totalDvAtmo": 1850,
  "stage.totalDvVac": 1850,
  "heat.backend": "system_heat",
  "heat.systemHeatStatus": "known",
  "heat.generatedKw": 284.2,
  "heat.removedKw": 301.6,
  "heat.netKw": -17.4,
  "heat.loops": [
    {
      id: "1",
      tempK: 771,
      nominalTempK: 800,
      genKw: 215,
      remKw: 155,
      netKw: 60,
      producers: [
        { name: "Reactor", role: "producer", fluxKw: 120 },
        { name: "Drill", role: "producer", count: 2, fluxKw: 95 },
      ],
      radiators: [{ name: "Radiator", role: "radiator", count: 4, fluxKw: -155 }],
      timeToCriticalSeconds: 260,
    },
    { id: "0", tempK: 612.4, nominalTempK: 800, genKw: 166.6, remKw: 201.6, netKw: -35 },
    { id: "2", tempK: 340, nominalTempK: 1200, genKw: 100, remKw: 100, netKw: 0 },
  ],
  "elec.reactors": [
    { partId: 42011, name: "MX-2C Hyperion Fission Reactor", on: true, status: "Online", ecPerSec: 36.4, ecMax: 40, coreTemp: 905, nominalTemp: 900, integrity: 98.7, fuel: "12y 184d", throttle: 91 },
    { partId: 42012, name: "MX-1B Hermes Fission Reactor", on: false, status: "Offline", ecPerSec: 0, ecMax: 18, coreTemp: 411, nominalTemp: 850, integrity: 100, fuel: "24y 12d", throttle: 0 },
  ],
  "elec.reactorsStatus": "known",
  "elec.totalGenEcPerSec": 48.6,
  "elec.otherEcPerSec": 1.2,
  "elec.netEcPerSec": 6.2,
  "elec.drawEcPerSec": 42.4,
  "elec.flowState": "valid",
  "solar.count": 4,
  "solar.outputEcPerSec": 9.8,
  "solar.efficiency": 0.87,
  "rtg.count": 1,
  "rtg.outputEcPerSec": 1.2,
  "sci.krpc.total": 42.7,
  "sci.krpc.transmitTotal": 19.4,
  "sci.krpc.count": 3,
  "sci.krpc.experiments": [
    { title: "Mystery Goo observation from space near Kerbin", value: 18.2, transmit: 5.5, data: 10 },
    { title: "Temperature scan from high space over Kerbin", value: 14.5, transmit: 11.6, data: 8 },
    { title: "Crew report from space near Kerbin", value: 10, transmit: 2.3, data: 5 },
  ],
  "sci.krpc.backend": "VesselScience",
  "sci.krpc.labTelemetryAvailable": true,
  "sci.krpc.labDaySeconds": 21_600,
  "sci.krpc.labCount": 1,
  "sci.alarmProviders": { kac: true, stock: true },
  "sci.krpc.failedLabCount": 0,
  "sci.krpc.malformedLabCount": 0,
  "sci.krpc.labs": [{
    id: "42001:1",
    title: "PX-L2 'Fate' Deep-Space Laboratory Module",
    dataStored: 1_455.199,
    dataCapacity: 1_500,
    scienceStored: 2.484,
    scienceCapacity: 500,
    calculatedSciencePerDay: 53.042,
    sciencePerDay: 53.042,
    scienceMultiplier: 5,
    crewCount: 3,
    scientistCount: 3,
    crewRequired: 1,
    scientistFactor: 6.75,
    converterAvailable: true,
    researchEnabled: true,
    operational: true,
    converterStatus: "Researching",
    lastTimeFactor: 1,
    state: "researching",
    etaKind: "finite",
    etaSeconds: 209_860.3,
  }],
  "career.science": 384.7,
  "tar.name": "Odyssey Station Docking Port",
  "tar.type": "dockingport",
  "tar.objectId": "8080",
  "tar.distance": 184.6,
  "tar.o.relativeVelocity": 2.3,
  "tar.o.velocity": 2_291.4,
  "tar.o.ApA": 105_812,
  "tar.o.PeA": 79_212,
  "tar.o.inclination": 0.51,
  "dock.x": 0.8,
  "dock.y": -0.4,
  "dock.axial": 184.5,
  "dock.ax": 2.1,
  "dock.ay": -1.3,
  ...notesFixture,
  "notes.pinned": activeNote,
  "notes.pinnedPath": activeNote.relativePath,
};

export const editorTelemetryFixture: TelemetrySnapshot = {
  ...representativeElectricityFixture,
  "context.mode": "editor",
  "flight.active": false,
  "identity.available": true,
  "game.saveFolder": "WMC Fixture Save",
  "editor.craftName": "Dual-condition regression craft",
  "editor.craftPersistentId": "9001",
  "editor.rootPartPersistentId": "1001",
  "editor.partPersistentIds": ["1001", "1002", "1003"],
  "editor.facility": "VAB",
  "editor.body": "Kerbin",
  "editor.bodies": ["Kerbin", "Mun", "Minmus", "Duna"],
  "editor.altitude": 0,
  "editor.mach": 0,
  "editor.revision": 7,
  "editor.analysisRevision": 7,
  "editor.stable": true,
  "editor.summaryAvailable": true,
  "editor.partCount": 31,
  "editor.crewCapacity": 3,
  "editor.stageCount": 10,
  "editor.wetMass": 18.742,
  "editor.dryMass": 7.416,
  "editor.resourceMass": 11.326,
  "editor.totalCost": 42580,
  "editor.dryCost": 39740,
  "editor.resourceCost": 2840,
  "editor.res.names": ["ElectricCharge", "LiquidFuel", "Oxidizer", "MonoPropellant"],
  "editor.res[ElectricCharge]": 1200,
  "editor.resMax[ElectricCharge]": 1200,
  "editor.res[LiquidFuel]": 810,
  "editor.resMax[LiquidFuel]": 810,
  "editor.res[Oxidizer]": 990,
  "editor.resMax[Oxidizer]": 990,
  "editor.res[MonoPropellant]": 30,
  "editor.resMax[MonoPropellant]": 30,
  "stage.available": true,
  "stage.complete": true,
  "stage.pending": false,
  "stage.count": 10,
  "stage.currentKsp": 9,
  "stage.unpoweredCount": 2,
  "stage.stages": denseEditorStages,
  "stage.totalDvAtmo": 4460,
  "stage.totalDvVac": 5470,
  "stage.totalBurnSeconds": 335,
  ...notesFixture,
};

export const fractionalStageElectricChargeFixture: TelemetrySnapshot = {
  ...flightTelemetryFixture,
  "v.name": "Untitled Space Craft",
  "res.names": ["ElectricCharge", "LiquidFuel", "Oxidizer"],
  "r.resource[ElectricCharge]": 6421.2319,
  "r.resourceMax[ElectricCharge]": 6430.6001,
  "r.resourceCurrent[ElectricCharge]": 0,
  "r.resourceCurrentMax[ElectricCharge]": 0.4,
  "r.resource[LiquidFuel]": 2160,
  "r.resourceMax[LiquidFuel]": 2160,
  "r.resourceCurrent[LiquidFuel]": 1440,
  "r.resourceCurrentMax[LiquidFuel]": 1440,
  "r.resource[Oxidizer]": 2640,
  "r.resourceMax[Oxidizer]": 2640,
  "r.resourceCurrent[Oxidizer]": 1760,
  "r.resourceCurrentMax[Oxidizer]": 1760,
  "res.stageResourceStage": 1,
  "stage.currentKsp": 3,
};

export const inactiveTelemetryFixture: TelemetrySnapshot = {
  "context.mode": "inactive",
  "flight.active": false,
  "v.name": "",
  "t.universalTime": 9_493_824,
  "mj.transfer.available": true,
  "mj.transfer.compatibilityReady": true,
  "mj.transfer.windows.requestId": "fixture-transfer-windows",
  "mj.transfer.windows.state": "completed",
  "mj.transfer.windows.origin": "Kerbin",
  "mj.transfer.windows.completedCount": 9,
  "mj.transfer.windows.totalCount": 9,
  "mj.transfer.windows.progress": 100,
  "mj.transfer.windows.refreshedAtUT": 9_493_700,
  "mj.transfer.windows.results": [
    { destination: "Moho", departureUT: 9_533_824, arrivalUT: 9_933_824, transferTime: 400_000 },
    { destination: "Dres", departureUT: 9_573_824, arrivalUT: 10_373_824, transferTime: 800_000 },
    { destination: "Neidon", departureUT: 9_613_824, arrivalUT: 12_613_824, transferTime: 3_000_000 },
    { destination: "Urlum", departureUT: 9_653_824, arrivalUT: 12_053_824, transferTime: 2_400_000 },
    { destination: "Jool", departureUT: 10_093_824, arrivalUT: 11_293_824, transferTime: 1_200_000 },
    { destination: "Duna", departureUT: 9_553_824, arrivalUT: 10_153_824, transferTime: 600_000 },
    { destination: "Eve", departureUT: 9_733_824, arrivalUT: 10_133_824, transferTime: 400_000 },
    { destination: "Plock", departureUT: 10_393_824, arrivalUT: 13_993_824, transferTime: 3_600_000 },
    { destination: "Sarnus", departureUT: 10_693_824, arrivalUT: 13_493_824, transferTime: 2_800_000 },
  ],
  "overview.scene": "Tracking Station",
  "overview.gameMode": "Career",
  "overview.readOnly": false,
  "overview.capabilities": { funds: true, science: true, reputation: true, contracts: true },
  "overview.funds": 1_284_650,
  "overview.science": 384.7,
  "overview.reputation": 72.4,
  "overview.contractCounts": { active: 3, offered: 5, completed: 28, failed: 1 },
  "overview.contracts": [
    {
      objectId: "201", title: "Explore Duna", type: "Exploration", deadline: 13_200_000,
      synopsis: "Carry the space program's exploration campaign to Duna and return useful flight data.",
      description: "Reach the Duna system, establish a stable orbit, and transmit or recover scientific observations gathered there.",
      notes: "Any active vessel may satisfy these objectives unless an objective says otherwise.",
      parameters: [
        { title: "Enter Duna's sphere of influence", status: "complete" },
        { title: "Orbit Duna", status: "incomplete" },
        { title: "Transmit or recover science from Duna", status: "incomplete" },
      ],
      fundsCompletion: 185_000, reputationCompletion: 22, scienceCompletion: 8,
    },
    {
      objectId: "202", title: "Position a satellite in polar orbit", type: "Satellite", deadline: 10_800_000,
      synopsis: "Place a new unmanned satellite into the requested polar orbit.",
      parameters: [
        { title: "Launch a new unmanned probe", status: "complete" },
        { title: "Maintain the specified inclination and altitude", status: "incomplete" },
        { title: "Keep the probe powered and controllable", status: "incomplete", optional: true },
      ],
      fundsCompletion: 92_500, reputationCompletion: 12,
    },
    {
      objectId: "203", title: "Gather temperature data from Minmus", type: "Science", deadline: 11_400_000,
      synopsis: "Collect temperature readings from the requested Minmus survey sites.",
      parameters: [
        { title: "Take a temperature scan in the Minmus Highlands", status: "complete" },
        { title: "Take a temperature scan in the Greater Flats", status: "incomplete" },
      ],
      fundsCompletion: 68_000, reputationCompletion: 7, scienceCompletion: 14,
    },
  ],
  "overview.vessels": [
    { objectId: "101", guid: "mock-odyssey-guid", name: "Odyssey", type: "Ship", situation: "Orbiting", body: "Kerbin", met: 134.2, crewCount: 3, crewNames: ["Jebediah Kerman", "Bill Kerman", "Bob Kerman"], recoverable: false, mission: true, apoapsisAltitude: 122_480, periapsisAltitude: 118_920, inclination: 0.12, period: 2_080.4, eccentricity: 0.0008 },
    { objectId: "102", name: "Mun Surveyor", type: "Probe", situation: "Orbiting", body: "Mun", met: 282_844, crewCount: 0, crewNames: [], recoverable: false, mission: true },
    { objectId: "103", guid: "mock-duna-relay-guid", name: "Duna Relay 1", type: "Relay", situation: "Orbiting", body: "Duna", met: 2_488_000, crewCount: 0, crewNames: [], recoverable: false, mission: true, apoapsisAltitude: 2_880_420, periapsisAltitude: 2_879_610, inclination: 0.04, period: 18_152.6, eccentricity: 0.0001 },
    { objectId: "104", name: "Kerbin Gateway", type: "Station", situation: "Orbiting", body: "Kerbin", met: 1_282_000, crewCount: 6, crewNames: ["Gene Kerman", "Linus Kerman", "Wernher Kerman", "Mortimer Kerman", "Walt Kerman", "Gus Kerman"], recoverable: false, mission: true },
    { objectId: "105", name: "Minmus Hopper", type: "Lander", situation: "Landed", body: "Minmus", met: 92_300, crewCount: 2, crewNames: ["Ed Kerman", "Al Kerman"], recoverable: false, mission: true },
    { objectId: "106", name: "Duna Pathfinder", type: "Rover", situation: "Landed", body: "Duna", met: 3_104_000, crewCount: 0, crewNames: [], recoverable: false, mission: true },
    { objectId: "107", guid: "mock-ksc-plane-guid", name: "KSC Survey Plane", type: "Plane", situation: "Landed", body: "Kerbin", met: 8_420, crewCount: 1, crewNames: ["Valentina Kerman"], recoverable: true, mission: true },
    { objectId: "108", name: "Minmus Research Base", type: "Base", situation: "Landed", body: "Minmus", met: 846_000, crewCount: 4, mission: true },
    { objectId: "109", name: "Jebediah Kerman", type: "EVA", situation: "Orbiting", body: "Kerbin", met: 780, crewCount: 1, mission: true },
    { objectId: "110", name: "Kerbin Orbital Tug", type: "Ship", situation: "Orbiting", body: "Kerbin", met: 184_200, crewCount: 2, mission: true },
    { objectId: "111", name: "Moho Scanner", type: "Probe", situation: "Orbiting", body: "Moho", met: 4_824_000, crewCount: 0, mission: true },
    { objectId: "112", name: "Ike Relay 2", type: "Relay", situation: "Orbiting", body: "Ike", met: 2_812_000, crewCount: 0, mission: true },
    { objectId: "113", name: "Mun Polar Rover", type: "Rover", situation: "Landed", body: "Mun", met: 382_000, crewCount: 0, mission: true },
    { objectId: "114", name: "KSC Flag", type: "Flag", situation: "Landed", body: "Kerbin", met: 5_122_000, crewCount: 0, mission: false },
    { objectId: "115", name: "Spent Kerbodyne Stage", type: "Debris", situation: "Sub Orbital", body: "Kerbin", met: 1_240, crewCount: 0, mission: false },
    { objectId: "116", name: "Comet SWM-204", type: "Space Object", situation: "Orbiting", body: "Sun", met: 8_422_000, crewCount: 0, mission: false },
  ],
  "overview.vesselsTruncated": false,
  "overview.vesselTerminationAvailable": true,
  "overview.rosterAvailable": true,
  "overview.roster": [
    { name: "Jebediah Kerman", assignment: "Odyssey", status: "Assigned", type: "Crew", trait: "Pilot", experience: 18.2, level: 3, veteran: true, flightCount: 8 },
    { name: "Bill Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 9.5, level: 2, veteran: true, flightCount: 5 },
    { name: "Bob Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 12.1, level: 2, veteran: true, flightCount: 6 },
    { name: "Valentina Kerman", status: "Dead", type: "Crew", trait: "Pilot", experience: 22, level: 4, veteran: true, flightCount: 11 },
    { name: "Linus Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 4.2, level: 1, veteran: false, flightCount: 2 },
    { name: "Wernher Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 7.1, level: 2, veteran: false, flightCount: 4 },
    { name: "Gene Kerman", assignment: "Kerbin Gateway", status: "Assigned", type: "Crew", trait: "Pilot", experience: 15.8, level: 3, veteran: false, flightCount: 7 },
    { name: "Mortimer Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 2.5, level: 1, veteran: false, flightCount: 1 },
    { name: "Walt Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 6.4, level: 2, veteran: false, flightCount: 3 },
    { name: "Gus Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 11.2, level: 2, veteran: false, flightCount: 5 },
    { name: "Ed Kerman", assignment: "Minmus Hopper", status: "Assigned", type: "Crew", trait: "Pilot", experience: 8.7, level: 2, veteran: false, flightCount: 4 },
    { name: "Al Kerman", status: "Available", type: "Crew", trait: "Scientist", experience: 3.8, level: 1, veteran: false, flightCount: 2 },
    { name: "Werner Kerman", status: "Available", type: "Crew", trait: "Engineer", experience: 5.6, level: 1, veteran: false, flightCount: 3 },
  ],
  "overview.alarms": [
    { title: "Odyssey maneuver", type: "Maneuver", time: 9_496_400, source: "Stock", vessel: "Odyssey" },
    { title: "Mun Surveyor SOI change", type: "SOI Change", time: 9_520_000, source: "KAC", vessel: "Mun Surveyor" },
  ],
  "overview.alarmProviders": { stock: "available", kac: "available" },
  "overview.refreshSeconds": { economy: 2, alarms: 2, fleet: 5, contracts: 10, roster: 15 },
  ...notesFixture,
};
